### ISSUE TITLE
Can not enable at Prestashop 1.6.1.15.

### ISSUE THREAD

**Issue by kongkiat** [omise/omise-prestashop#69] opened 2018-08-16 17:12 UTC
1. It can not enable at Prestashop 1.6.1.15.
2. It can not configuation error "You do not have permission to configure this module.".

**Comment by hassadee** [comment] 2018-08-16 23:07
It happen with PrestaShop 1.6.1.20 too.
You can upload zip file of the module, but can't click to install.

**Comment by jonrandy** [comment] 2018-08-17 04:52
Hi there. As yet I have been unable to reproduce this issue. Did you remove the previous version of the plugin before installing the new one? Or install over the top?

**Comment by kongkiat** [comment] 2018-08-17 06:44
Hi,
I uninstall and delete previous version, Before install new..

**Comment by jonrandy** [comment] 2018-08-20 09:55
@hassadee I've just tried an install on version 1.6.1.19 and also on 1.6.1.20, and had no problems.
Can you give me the details of your system? PHP version, webserver etc. I'm sure it probably isn't  related, but I'm just trying to get as much information as possible

**Comment by jonrandy** [comment] 2018-08-20 09:56
@kongkiat Do you have full superadmin privileges?

**Comment by hassadee** [comment] 2018-08-20 12:56
@jonrandy Umm strange... my PrestaShop version is 1.6.1.19, PHP version 5.6.32, and my Web Server is Apache.

**Comment by jonrandy** [comment] 2018-08-21 03:23
@hassadee Did you uninstall the previous version? Do you have full admin privileges? Can you successfully install other modules?

**Comment by jonrandy** [comment] 2018-08-21 03:30
@hassadee Did you uninstall the previous version? Do you have full admin privileges? Can you successfully install other modules?

**Comment by jonrandy** [comment] 2018-09-17 07:45
Still having trouble with this?

**Comment by hassadee** [comment] 2018-09-17 09:28
@jonrandy Still. I working with 2 versions of PrestaShop v1.6.1.19 and v1.7.2, and it only works with v1.7.2 but doesn't work with 1.6.1.19

**Comment by aashishgurung** [comment] 2023-03-10 08:49
We’re going to close this since there hasn’t been any activity on this issue for a while. If you think it's still relevant, please feel free to reopen it with more details and we’ll take another look.

**Closed as completed by aashishgurung** 2023-03-10 08:49 UTC
